require File.expand_path('../config/application', __FILE__)
require 'rake'
require 'rspec/core/rake_task'

RailsAppSample::Application.load_tasks

RSpec::Core::RakeTask.new('test:ops') do |test|
  test.pattern = 'spec/functional/*_spec.rb'
end
