$LOAD_PATH.unshift File.dirname(__FILE__) + '/../../lib'
$LOAD_PATH.unshift File.dirname(__FILE__) unless $LOAD_PATH.include?(File.dirname(__FILE__))

require 'rspec/core/rake_task'

desc 'Start the demo using `rackup`'
task :start do
  exec 'rackup config.ru'
end

task default: [:start]

RSpec::Core::RakeTask.new('test:ops') do |test|
  test.pattern = 'spec/functional/*_spec.rb'
end
