#!/bin/sh

set -e

cd "$(dirname "$0")/.."

script/setup

echo "===> Running rubocop linter"
if [ -n "$1" ] && [ "$1" = "-a" ]; then
  auto_correct="--auto-correct"
fi

bundle exec rubocop -D $auto_correct

if [ -n "$1" ] && [ "$1" = "-a" ]; then
  # pass arguments to test call. This is useful for calling a single test.
  bundle exec rspec "$1"
else
  bundle exec rspec
fi
